// Category operation and constance
export const GET_CATEGORY_LIST = "LOAD_CATEGORY_LIST";
export const CATEGORY_LOADING = "CATEGORY_LOADING";

//Course operation
export const GET_COURSELIST = "GET_LOADCOURSELIST";
export const COURSELIST_LOADING = "COURSELIST_LOADING";

export const GET_TEACHPLAN_LIST = "LOADTEACHPLANLIST";
export const TEACHPLANLIST_LOADING = "CATEGORY_LOADING";

export const COURSEBASIC_ADD = "COURSEBASIC_ADD";
export const COURSEBASIC_ADD_LOADING = "COURSEBASIC_ADD_LOADING";
export const COURSEBASIC_GET = "COURSEBASIC_GET";
export const COURSEBASIC_GET_LOADING = "COURSEBASIC_GET_LOADING";

// Dictionary operation
export const GET_DICTIONARY = "GET_DICTIONARY";
export const DICTIONARY_LOADING = "DICTIONARY_LOADING";
